### PR TITLE
Add build and push actions

### PR DESCRIPTION
**Pull request by lcc3108**
Add build and push at harbor

### CODE REVIEW

**Review by pjainxido — DISMISSED** [review]

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
Update repo fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-9.micalgenus.com)

**Pull request merged**
