### PR TITLE
Nextjs test coverage

### PR DESCRIPTION
**Pull request by micalgenus**

### CODE REVIEW

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by micalgenus** [comment]
https://moomark-dev.micalgenus.com/pr/25

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-25.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-25.micalgenus.com)

**Review by pjainxido — APPROVED** [review]
LGTM!

**Pull request merged**
