### PR TITLE
Refactor Post Page 

### PR DESCRIPTION
**Pull request by pjainxido**
- comment 컴포넌트 리팩토링, 스타일수정
- post viewer 개선

### CODE REVIEW

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-23.micalgenus.com)

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-23.micalgenus.com)

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-23.micalgenus.com)

**Review by micalgenus — APPROVED** [review]

**Pull request merged**
