### PR TITLE
GlobalHeader Scroll popup/down

### PR DESCRIPTION
**Pull request by pjainxido**

### CODE REVIEW

**Comment by blackcowmooo** [comment]
Update repo fail

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-dev.micalgenus.com/pr\/37)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-dev.micalgenus.com/pr\/37)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-dev.micalgenus.com/pr\/37)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-dev.micalgenus.com/pr\/37)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-dev.micalgenus.com/pr\/37)

**Review by micalgenus — APPROVED** [review]

**Pull request merged**
