### PR TITLE
Editor Theme

### PR DESCRIPTION
**Pull request by pjainxido**
- theme 에 맞게 에디터 테마 적용로직 추가
- taglist 스타일 수정
- recoil selector가 불필요한 state 및 key value 수정

### CODE REVIEW

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-30.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-30.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-30.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-30.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-dev.micalgenus.com/pr\/30)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-dev.micalgenus.com/pr\/30)

**Review by lcc3108 — APPROVED** [review]

**Pull request merged**
