### PR TITLE
main page #6

### PR DESCRIPTION
**Pull request by pjainxido**
- 메인페이지 내에 게시물 리스트 뷰 컴포넌트 
- 게시물 검색 필터 옵션 ( 최신검색결과, 추천게시물(인기) ) 추가

### CODE REVIEW

**Comment by lcc3108** [comment]
그.. 린트 페일인데스

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:3d9957a" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: @types/react@17.0.14
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.8.0" from react-apollo@3.1.5
npm ERR! node_modules/react-apollo
npm ERR!   react-apollo@"^3.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-11T16_15_20_474Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:b3ffcaf" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: @types/react@17.0.14
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.8.0" from react-apollo@3.1.5
npm ERR! node_modules/react-apollo
npm ERR!   react-apollo@"^3.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T13_34_17_149Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:54d42dc" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: @types/react@17.0.14
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.8.0" from react-apollo@3.1.5
npm ERR! node_modules/react-apollo
npm ERR!   react-apollo@"^3.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T14_21_34_342Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:21c83d5" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: @types/react@17.0.14
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.8.0" from react-apollo@3.1.5
npm ERR! node_modules/react-apollo
npm ERR!   react-apollo@"^3.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T14_24_46_337Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:7400272" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: @types/react@17.0.14
npm ERR! node_modules/@types/react
npm ERR!   @types/react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.8.0" from react-apollo@3.1.5
npm ERR! node_modules/react-apollo
npm ERR!   react-apollo@"^3.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T14_46_55_746Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:2d37c7d" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: @types/react@17.0.14
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.8.0" from react-apollo@3.1.5
npm ERR! node_modules/react-apollo
npm ERR!   react-apollo@"^3.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T14_58_25_840Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:5141677" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: @types/react@17.0.14
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^17.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^16.8.0" from react-apollo@3.1.5
npm ERR! node_modules/react-apollo
npm ERR!   react-apollo@"^3.1.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T15_14_57_257Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:d537646" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: antd@4.16.7
npm ERR! node_modules/antd
npm ERR!   antd@"^4.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer antd@"^3.2.0" from antd-scss-theme-plugin@1.0.8
npm ERR! node_modules/antd-scss-theme-plugin
npm ERR!   dev antd-scss-theme-plugin@"^1.0.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T15_19_27_754Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
build fail<details><summary>Detail</summary>[36m===> DETECTING[0m
======== Output: heroku/ruby@0.0.1 ========
no
err:  heroku/ruby@0.0.1 (1)
[33;1mWarning: [0mWarning: buildpack heroku/jvm has a "version" key. This key is deprecated in build plan requirements in buildpack API 0.3. "metadata.version" should be used instead
heroku/nodejs-engine     0.7.4
heroku/nodejs-npm        0.4.4
heroku/nodejs-typescript 0.2.3
heroku/procfile          0.6.2
[36m===> ANALYZING[0m
Previous image with name "harbor.micalgenus.com/pr/moomark-frontend:119aaed" not found
[36m===> RESTORING[0m
[36m===> BUILDING[0m
[INFO] Node.js Buildpack
[INFO] Setting NODE_ENV to production
[INFO] Installing toolbox
[INFO] - yj

[1;35m[Installing Node][0m
[INFO] Getting Node version
[INFO] Resolving Node version
[INFO] Downloading and extracting Node v16.4.2

[1;35m[Parsing package.json][0m
[INFO] Parsing package.json

[1;35m[Installing yarn][0m
[INFO] Installing yarn@1.22.10
[INFO] No file to start server
[INFO] either use 'docker run' to start container or add index.js or server.js
[INFO] Using npm v7.18.1 from Node
[INFO] Installing node modules
npm notice 
npm notice New minor version of npm available! 7.18.1 -> 7.19.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.19.1>
npm notice Run `npm install -g npm@7.19.1` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: moomark-front@0.0.1
npm ERR! Found: antd@4.16.7
npm ERR! node_modules/antd
npm ERR!   antd@"^4.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer antd@"^3.2.0" from antd-scss-theme-plugin@1.0.8
npm ERR! node_modules/antd-scss-theme-plugin
npm ERR!   dev antd-scss-theme-plugin@"^1.0.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/heroku/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/heroku/.npm/_logs/2021-07-12T15_25_29_116Z-debug.log
[31;1mERROR: [0mfailed to build: exit status 1</details>

**Comment by blackcowmooo** [comment]
http://moomark-frontend-pr-6.micalgenus.com

**Review by lcc3108 — APPROVED** [review]

**Review by Apisapple — APPROVED** [review]

**Pull request merged**
