### PR TITLE
Fix Main Logo scroll Click not open in new tab & Theme toggle bug

### PR DESCRIPTION
**Pull request by pjainxido**

### CODE REVIEW

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
Update repo fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
Update repo fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Review by micalgenus — DISMISSED** [review]

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-frontend-pr-28.micalgenus.com)

**Review by micalgenus — APPROVED** [review]

**Pull request merged**
